# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f76c80a65be24c2f9ad5648976793677969e3f917ae0c3d6e56a6fa68c0c6e76d9d3951ad95ff7cce85c910575f8260d1c4b0527e25f32da0e19ee05e6d1057d

test:
  secret_key_base: 5e5f708ab40c7e4ceecbfa07dfaf1966ed12b7a15b7fb057c3d2f833f12e5c9e2f8d9ae05815ee367e4cdc98e2e9eddf7800d3fc74e58c8a945d7c6859038ab6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
