# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: daa9c1094351deb11bd9e0fee1227da83da0b751753928ad57bf46836eacf86c8d28599bac065515023bcaec0c0fb8dd843baaa7a3af704ebb0f19f8a792911d

test:
  secret_key_base: c7659383cf74b1d9954bf86015cdd450db2ccba9151a0c4e36cc2505ab27446211909b1156eb1469067828755d4da3ae0bb2406cd2b42a8927afe8e4e401c265

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
